CREATE TABLE IF NOT EXISTS livres (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(80) NOT NULL,
    auteur VARCHAR(40) NOT NULL,
    total INT UNSIGNED NOT NULL,
    pret INT UNSIGNED NOT NULL DEFAULT 0
);
