# Configuration du serveur
server.port=8080

# Datasource
# url de la base de données H2 "testdb"
spring.datasource.url=jdbc:h2:mem:testdb
# driver utilisé
spring.datasource.driver-class-name=org.h2.Driver
# login d'accès à la base de données
spring.datasource.username=sa
# mot de passe d'accès à la base de données
spring.datasource.password=

# Génération de la base de données sur la base des entités définies
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Outils de logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuration H2 Console (accessible via http://localhost:8080/h2)
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Configuration JSON
spring.jackson.serialization.fail-on-empty-beans=false
